### ISSUE TITLE
protoboard poi sometimes restarts

### ISSUE THREAD

**Issue by 5ch4um1** [tomjuggler/SmartPoiOffline#1]
I tried to build a 16px version of these offline poi, and apart from still having some issues with the colours, my protoboard poi sometimes restarts itself while spinning?
![IMG_20201113_203058](https://user-images.githubusercontent.com/36307725/99131449-155f6080-260b-11eb-8747-863122eaef04.jpg)
should i maybe solder things together?
anyway, the first test pattern i tried looks quite nice! 
![IMG_20201113_221059](https://user-images.githubusercontent.com/36307725/99131517-49d31c80-260b-11eb-917b-bde3acc42116.jpg)
and jokes aside, thank you so much for this cool project, can't believe that there are not more contributors, if i can help with anything, please let me know.
 I'm waiting for 2 wemos d1 minis to arrive and then will try the "online" version too! :)

**Comment by tomjuggler** [comment]
Thanks for the kind words. I kind of threw this program together and didn't test it much. Let me know if the update solves the problem. Good luck with the D1 mini's, remember to start with the emulator version! The project is detailed here: https://www.circusscientist.com/smart-poi-overview/ - please add your email to the mailing list, I will hopefully have time to do more upgrades in January and you will hear about it there first. I hope you have an Android device, most of the functionality now resides in the accompanying app. 

By the way, how did you get the image you are using into the correct format? I don't think I shared that code, for the offline version at least...

**Comment by 5ch4um1** [comment]
Left my email in the form on your website yesterday. :) 
I really appreciate all your work and will happily help with testing and give some feedback! 
As for the image, i would have probably been faster typing that array by hand, but i learned a lot about the bitmap image format, c arrays, got a nice example to memorize the difference between unsigned and signed, it was a lot of fun...
finally used an online converter that accepted png and gave me an unsigned array. and since it was just one colour, i just did a search and replace, but somehow still all pixels are red, will look into this further today! i read a bit about those ws2812 (or 13, not sure) i'm using, so, basically, they want a 16 bit rgb value if i understand that right? since it's just 16 px, i asked myself if i could just save an array in the format those leds want and skip the conversion...? probably yes i guess... 
anyway, i'll try to post some updates to the readme of my fork. i really love the simplicity of this project, so far this runs just fine from a 1 cell powerbank, and another 16 leds should be no problem i guess. that was almost just plug and play yesterday, and adapt a bit of code for the leds. 
I think this is a super nice way to get people interested in the project. take a powerbank, an arduino and a ledstrip, get pixelpoi and have fun! no electronics skills needed, cheap parts, easily replaceable, low complexity for beginners, that's all pretty nice! :)

**Comment by 5ch4um1** [comment]
uhm, wait, in the code it says:
`uint8_t message1Data[] =`
but the array has signed values? this doesn't seem right?

**Comment by tomjuggler** [comment]
My whole life is a lie :-(

Seriously though, the Arduino compiler treats uint8_t and int8_t exactly the same. At some point I was doing arrays with 3 bytes per pixel (all values from 0-255) and just left the declaration the same since it didn't make a difference. I'm going to change it now, thanks for pointing that out.

**Comment by 5ch4um1** [comment]
I shouldn't have made that joke about my protoboard poi, i think i fried the voltage regulator of a nano clone... xD 
anyway, i was a bit busy these days, but now i finally made a somewhat more spinnable version, with 32 leds, to get 16 pixel, i'll post about my progress soon hopefully! :)
the RGBSetDemo already looks pretty awesome and super bright on some test fotos! 
now it would be nice to get some pixels, i'll try to figure out an easy way to convert the images.

**Comment by 5ch4um1** [comment]
i think i can say that soldering and mounting it around a powerbank with duct tape and a lot of hot glue, and protecting it with a plastic bottle seems to have fixed the issue... ;)
